AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudGuard - Serverless Security Compliance Automated Architecture

Parameters:
  AdminNotificationEmail:
    Type: String
    Description: Enter your personal email address to receive compliance alerts.

Resources:
  # 1. Decoupled Communication Topic
  CloudGuardSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloudguard-security-alerts
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !Ref AdminNotificationEmail
          Protocol: email

  # 2. Serverless Computing Resource
  # checkov:skip=CKV_AWS_116: "Dead Letter Queue is not required for a stateless read-only automated cron script."
  # checkov:skip=CKV_AWS_117: "VPC placement is unnecessary as the execution logic interacts solely with global AWS public endpoints."
  # checkov:skip=CKV_AWS_173: "Environment variables only map basic resource ARNs, eliminating the requirement for custom KMS configurations."
  CloudGuardScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.14
      Timeout: 30
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CloudGuardSNSTopic
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:ListUsers
                - iam:ListAccessKeys
                - iam:GetAccountSummary
              Resource: "*"
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref CloudGuardSNSTopic
      Events:
        MidnightScheduledAudit:
          Type: Schedule
          Properties:
            Schedule: "cron(0 0 * * ? *)"
            Name: CloudGuardDailyCron
            Description: Automated trigger for the CloudGuard compliance engine
            Enabled: True

Outputs:
  LambdaFunctionARN:
    Description: "CloudGuard Scanner Lambda Function ARN"
    Value: !GetAtt CloudGuardScannerFunction.Arn
  SNSTopicARN:
    Description: "CloudGuard SNS Topic ARN"
    Value: !Ref CloudGuardSNSTopic