name: CloudGuard Security Pipeline

on:
  push:
    branches: [ main ]

jobs:
  infrastructure-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: cloudformation